// Rich Demo Data for Chess Championship
// Automatically used when backend fixtures/standings are empty or zero.

export const DEMO_CHESS_STATS = {
  totalRegistrations: 48,
  registeredCount: 48,
  currentRound: 2,
  matchDuration: 10,
  liveMatches: 2,
  liveMatchesCount: 2,
  completedMatches: 14,
};

export const DEMO_CHESS_MATCHES = [
  {
    _id: 'chess_m_101',
    matchId: 'M-14',
    round: 2,
    roundName: 'Quarter Finals • Board 1',
    status: 'live',
    player1: {
      _id: 'p1',
      fullName: 'Aditya Sharma',
      department: 'Computer Science',
      rating: 1840,
    },
    player2: {
      _id: 'p2',
      fullName: 'Vikram Mehta',
      department: 'Mechanical Eng.',
      rating: 1795,
    },
    whitePlayer: 'player1',
    blackPlayer: 'player2',
    player1Material: 34,
    player2Material: 31,
    timeRemaining: 415,
    matchDuration: 10,
  },
  {
    _id: 'chess_m_102',
    matchId: 'M-15',
    round: 2,
    roundName: 'Quarter Finals • Board 2',
    status: 'live',
    player1: {
      _id: 'p3',
      fullName: 'Rohan Gupta',
      department: 'Electrical Eng.',
      rating: 1810,
    },
    player2: {
      _id: 'p4',
      fullName: 'Priya Patel',
      department: 'Information Tech.',
      rating: 1770,
    },
    whitePlayer: 'player1',
    blackPlayer: 'player2',
    player1Material: 28,
    player2Material: 29,
    timeRemaining: 290,
    matchDuration: 10,
  },
  {
    _id: 'chess_m_103',
    matchId: 'M-16',
    round: 2,
    roundName: 'Quarter Finals • Board 3',
    status: 'scheduled',
    player1: {
      _id: 'p5',
      fullName: 'Kabir Verma',
      department: 'Civil Engineering',
      rating: 1735,
    },
    player2: {
      _id: 'p6',
      fullName: 'Siddharth Sen',
      department: 'Electronics',
      rating: 1805,
    },
    whitePlayer: 'player1',
    blackPlayer: 'player2',
    scheduledTime: 'Today, 4:30 PM',
  },
  {
    _id: 'chess_m_104',
    matchId: 'M-11',
    round: 1,
    roundName: 'Round of 16',
    status: 'completed',
    player1: {
      _id: 'p1',
      fullName: 'Aditya Sharma',
      department: 'Computer Science',
    },
    player2: {
      _id: 'p7',
      fullName: 'Zaid Khan',
      department: 'Biotechnology',
    },
    winner: 'player1',
    result: '1 - 0',
    outcomeDetails: 'Checkmate (Move 38)',
    player1Material: 39,
    player2Material: 18,
  },
  {
    _id: 'chess_m_105',
    matchId: 'M-12',
    round: 1,
    roundName: 'Round of 16',
    status: 'completed',
    player1: {
      _id: 'p3',
      fullName: 'Rohan Gupta',
      department: 'Electrical Eng.',
    },
    player2: {
      _id: 'p8',
      fullName: 'Tanmay Joshi',
      department: 'Chemical Eng.',
    },
    winner: 'player1',
    result: '1 - 0',
    outcomeDetails: 'Resignation (Move 29)',
    player1Material: 32,
    player2Material: 21,
  },
  {
    _id: 'chess_m_106',
    matchId: 'M-13',
    round: 1,
    roundName: 'Round of 16',
    status: 'completed',
    player1: {
      _id: 'p4',
      fullName: 'Priya Patel',
      department: 'Information Tech.',
    },
    player2: {
      _id: 'p9',
      fullName: 'Farhan Ali',
      department: 'Mechanical Eng.',
    },
    winner: 'player1',
    result: '1 - 0',
    outcomeDetails: 'Time Forfeit (0:00)',
    player1Material: 35,
    player2Material: 27,
  },
];

export const DEMO_CHESS_STANDINGS = [
  {
    _id: 'p1',
    fullName: 'Aditya Sharma',
    department: 'Computer Science',
    tournamentPoints: 4.5,
    materialPoints: 112,
    matchesPlayed: 5,
    wins: 4,
    draws: 1,
    losses: 0,
  },
  {
    _id: 'p3',
    fullName: 'Rohan Gupta',
    department: 'Electrical Eng.',
    tournamentPoints: 4.0,
    materialPoints: 98,
    matchesPlayed: 5,
    wins: 4,
    draws: 0,
    losses: 1,
  },
  {
    _id: 'p4',
    fullName: 'Priya Patel',
    department: 'Information Tech.',
    tournamentPoints: 3.5,
    materialPoints: 91,
    matchesPlayed: 5,
    wins: 3,
    draws: 1,
    losses: 1,
  },
  {
    _id: 'p2',
    fullName: 'Vikram Mehta',
    department: 'Mechanical Eng.',
    tournamentPoints: 3.5,
    materialPoints: 86,
    matchesPlayed: 5,
    wins: 3,
    draws: 1,
    losses: 1,
  },
  {
    _id: 'p6',
    fullName: 'Siddharth Sen',
    department: 'Electronics',
    tournamentPoints: 3.0,
    materialPoints: 79,
    matchesPlayed: 5,
    wins: 3,
    draws: 0,
    losses: 2,
  },
  {
    _id: 'p5',
    fullName: 'Kabir Verma',
    department: 'Civil Engineering',
    tournamentPoints: 2.5,
    materialPoints: 72,
    matchesPlayed: 4,
    wins: 2,
    draws: 1,
    losses: 1,
  },
];

export const DEMO_CHESS_PLAYERS = [
  {
    _id: 'p1',
    fullName: 'Aditya Sharma',
    department: 'Computer Science',
    rating: 1840,
    matchesPlayed: 5,
    wins: 4,
    draws: 1,
    losses: 0,
    tournamentPoints: 4.5,
  },
  {
    _id: 'p3',
    fullName: 'Rohan Gupta',
    department: 'Electrical Eng.',
    rating: 1810,
    matchesPlayed: 5,
    wins: 4,
    draws: 0,
    losses: 1,
    tournamentPoints: 4.0,
  },
  {
    _id: 'p4',
    fullName: 'Priya Patel',
    department: 'Information Tech.',
    rating: 1770,
    matchesPlayed: 5,
    wins: 3,
    draws: 1,
    losses: 1,
    tournamentPoints: 3.5,
  },
  {
    _id: 'p2',
    fullName: 'Vikram Mehta',
    department: 'Mechanical Eng.',
    rating: 1795,
    matchesPlayed: 5,
    wins: 3,
    draws: 1,
    losses: 1,
    tournamentPoints: 3.5,
  },
  {
    _id: 'p6',
    fullName: 'Siddharth Sen',
    department: 'Electronics',
    rating: 1805,
    matchesPlayed: 5,
    wins: 3,
    draws: 0,
    losses: 2,
    tournamentPoints: 3.0,
  },
  {
    _id: 'p5',
    fullName: 'Kabir Verma',
    department: 'Civil Engineering',
    rating: 1735,
    matchesPlayed: 4,
    wins: 2,
    draws: 1,
    losses: 1,
    tournamentPoints: 2.5,
  },
];
