'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import { Trophy, ExternalLink, ZoomIn, ZoomOut, RotateCcw } from 'lucide-react';
import { StatusBadge, BoardNumberBadge } from '@/components/ui/Badge';

export const BracketView = ({ rounds, category, isLocked, isPublished }) => {
  const { isAdmin } = useAuth();
  const [zoom, setZoom] = useState(1);

  if (!rounds || rounds.length === 0) {
    return (
      <div className="p-12 text-center sport-card">
        <Trophy className="w-10 h-10 text-[#64748B] mx-auto mb-3" />
        <h3 className="text-base font-bold text-white mb-1">No Draw Generated Yet</h3>
        <p className="text-xs text-[#94A3B8] max-w-sm mx-auto">
          The dynamic knockout bracket for this category has not been generated by the tournament administrator yet.
        </p>
        {isAdmin && (
          <div className="mt-4">
            <Link
              href="/admin/draws"
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-[#D4AF37] text-[#070B16] font-bold text-xs shadow-sm"
            >
              Generate Draw in Admin
            </Link>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Top controls: Category status, Zoom */}
      <div className="flex flex-wrap items-center justify-between gap-3 p-3.5 rounded-xl sport-card">
        <div className="flex items-center gap-3">
          <span className="text-xs text-[#94A3B8]">Status:</span>
          {isLocked ? (
            <span className="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-semibold bg-[#D4AF37]/10 text-[#D4AF37] border border-[#D4AF37]/20">
              Published & Locked
            </span>
          ) : (
            <span className="inline-flex items-center px-2 py-0.5 rounded text-[11px] font-semibold bg-amber-500/10 text-amber-400 border border-amber-500/20">
              Draft / Unlocked
            </span>
          )}
          <span className="text-xs text-[#64748B]">|</span>
          <span className="text-xs text-[#94A3B8]">{rounds.length} Knockout Rounds</span>
        </div>

        {/* Zoom controls */}
        <div className="flex items-center gap-1 bg-[#070B16] p-1 rounded-lg border border-[#1C2B48]">
          <button
            onClick={() => setZoom(Math.max(0.7, zoom - 0.1))}
            className="p-1 rounded text-[#94A3B8] hover:text-white transition-colors"
            title="Zoom Out"
          >
            <ZoomOut className="w-3.5 h-3.5" />
          </button>
          <span className="px-2 text-xs font-mono text-slate-300 font-semibold">{Math.round(zoom * 100)}%</span>
          <button
            onClick={() => setZoom(Math.min(1.4, zoom + 0.1))}
            className="p-1 rounded text-[#94A3B8] hover:text-white transition-colors"
            title="Zoom In"
          >
            <ZoomIn className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={() => setZoom(1)}
            className="p-1 rounded text-[#94A3B8] hover:text-white transition-colors ml-1"
            title="Reset"
          >
            <RotateCcw className="w-3 h-3" />
          </button>
        </div>
      </div>

      {/* Bracket Tree Container */}
      <div className="w-full overflow-x-auto overflow-y-hidden pb-8 pt-4 rounded-2xl bg-[#070B16] border border-[#1C2B48] p-6 min-h-[480px]">
        <div
          className="flex items-stretch gap-10 min-w-max transition-transform origin-top-left"
          style={{ transform: `scale(${zoom})` }}
        >
          {rounds.map((round, rIdx) => {
            const isFinal = rIdx === rounds.length - 1;
            return (
              <div key={round.roundNumber} className="flex flex-col w-68 shrink-0">
                {/* Round Header */}
                <div className="text-center pb-3 mb-4 border-b border-[#1C2B48]">
                  <span className="text-[10px] font-mono text-[#D4AF37] uppercase tracking-widest font-bold block">
                    Round {round.roundNumber}
                  </span>
                  <h4 className="text-sm font-bold font-display text-white">
                    {round.roundName}
                  </h4>
                  <span className="text-[10px] text-[#64748B]">
                    {round.matches.length} {round.matches.length === 1 ? 'Match' : 'Matches'}
                  </span>
                </div>

                {/* Match Cards Container */}
                <div className="flex flex-col justify-around flex-grow gap-5">
                  {round.matches.map((match) => (
                    <MatchNode
                      key={match._id}
                      match={match}
                      isFinal={isFinal}
                      isAdmin={isAdmin}
                    />
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

const MatchNode = ({ match, isFinal, isAdmin }) => {
  const isTeam1Winner = match.winnerTeam && match.team1 && (match.winnerTeam._id === match.team1._id || match.winnerTeam === match.team1._id);
  const isTeam2Winner = match.winnerTeam && match.team2 && (match.winnerTeam._id === match.team2._id || match.winnerTeam === match.team2._id);

  return (
    <div
      className={`rounded-xl border p-3 transition-all ${
        match.status === 'live'
          ? 'bg-[#0E1626] border-emerald-500/50'
          : match.status === 'completed'
          ? 'bg-[#0E1626] border-[#D4AF37]/30'
          : match.status === 'bye'
          ? 'bg-[#0E1626]/50 border-purple-500/20'
          : 'bg-[#0E1626] border-[#1C2B48]'
      }`}
    >
      {/* Node Meta: Match # & Status */}
      <div className="flex items-center justify-between gap-2 pb-2 mb-2 border-b border-[#1C2B48]/80 text-[10px]">
        <span className="font-mono text-[#94A3B8]">M#{match.matchNumber}</span>
        <StatusBadge status={match.status} queuePosition={match.queuePosition} />
      </div>

      {/* Team 1 Slot */}
      <div
        className={`flex items-center justify-between p-2 rounded-lg mb-1 ${
          isTeam1Winner
            ? 'bg-[#D4AF37]/10 text-[#D4AF37] font-bold border border-[#D4AF37]/20'
            : match.team1
            ? 'bg-[#070B16] text-slate-200'
            : 'bg-[#070B16]/50 text-slate-500 italic'
        }`}
      >
        <span className="truncate text-xs pr-2">
          {match.team1 ? match.team1.name : 'Waiting...'}
        </span>
        <span className="font-mono text-xs font-bold text-[#D4AF37] shrink-0">
          {match.finalScore?.team1BoardsWon || 0}
        </span>
      </div>

      {/* Team 2 Slot */}
      <div
        className={`flex items-center justify-between p-2 rounded-lg ${
          match.isBye
            ? 'bg-purple-500/10 text-purple-300 italic'
            : isTeam2Winner
            ? 'bg-[#D4AF37]/10 text-[#D4AF37] font-bold border border-[#D4AF37]/20'
            : match.team2
            ? 'bg-[#070B16] text-slate-200'
            : 'bg-[#070B16]/50 text-slate-500 italic'
        }`}
      >
        <span className="truncate text-xs pr-2">
          {match.isBye ? 'BYE (Automatic Advance)' : match.team2 ? match.team2.name : 'Waiting...'}
        </span>
        {!match.isBye && (
          <span className="font-mono text-xs font-bold text-[#D4AF37] shrink-0">
            {match.finalScore?.team2BoardsWon || 0}
          </span>
        )}
      </div>

      {/* Admin Quick Score Link */}
      {isAdmin && !match.isBye && match.team1 && match.team2 && (
        <div className="mt-2 pt-2 border-t border-[#1C2B48]/80 flex justify-end">
          <Link
            href={`/admin/matches/${match._id}/score`}
            className="flex items-center gap-1 text-[11px] font-semibold text-[#D4AF37] hover:underline"
          >
            <span>Score Match</span>
            <ExternalLink className="w-3 h-3" />
          </Link>
        </div>
      )}
    </div>
  );
};
