'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import { Trophy, ExternalLink, ZoomIn, ZoomOut, RotateCcw, Crown } from 'lucide-react';
import { StatusBadge, MainBoardBadge } from '@/components/ui/Badge';

export const BracketView = ({ rounds, category, isLocked, isPublished }) => {
  const { isAdmin } = useAuth();
  const [zoom, setZoom] = useState(1);

  if (!rounds || rounds.length === 0) {
    return (
      <div className="p-12 text-center sport-card">
        <Trophy className="w-12 h-12 text-[#FDB095] mx-auto mb-3 opacity-80" />
        <h3 className="text-lg font-black text-white font-display mb-1">No Bracket Generated Yet</h3>
        <p className="text-xs text-[#D8C7F0] max-w-sm mx-auto">
          The dynamic knockout bracket for this category has not been generated by the tournament administrator yet.
        </p>
        {isAdmin && (
          <div className="mt-5">
            <Link
              href="/admin/draws"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-2xl btn-gold text-xs font-black shadow-md"
            >
              Generate Draw in Admin →
            </Link>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {/* Top controls: Category status, Zoom */}
      <div className="flex flex-wrap items-center justify-between gap-3 p-4 rounded-2xl sport-card">
        <div className="flex items-center gap-3">
          <span className="text-xs text-[#D8C7F0] font-semibold">Status:</span>
          {isLocked ? (
            <span className="inline-flex items-center px-3 py-1 rounded-full text-[11px] font-bold bg-[#FFBA00]/15 text-[#FFBA00] border border-[#FFBA00]/30 font-mono">
              Published & Locked
            </span>
          ) : (
            <span className="inline-flex items-center px-3 py-1 rounded-full text-[11px] font-bold bg-[#FDB095]/15 text-[#FDB095] border border-[#FDB095]/30 font-mono">
              Draft / Unlocked
            </span>
          )}
          <span className="text-xs text-[#4A138C]">|</span>
          <span className="text-xs text-[#D8C7F0] font-mono">{rounds.length} Knockout Rounds</span>
        </div>

        {/* Zoom controls */}
        <div className="flex items-center gap-1.5 bg-[#140129] p-1.5 rounded-xl border border-[#4A138C]">
          <button
            onClick={() => setZoom(Math.max(0.7, zoom - 0.1))}
            className="p-1.5 rounded-lg text-[#D8C7F0] hover:text-white hover:bg-[#2C0854] transition-colors"
            title="Zoom Out"
          >
            <ZoomOut className="w-3.5 h-3.5" />
          </button>
          <span className="px-2 text-xs font-mono text-[#FFBA00] font-bold">{Math.round(zoom * 100)}%</span>
          <button
            onClick={() => setZoom(Math.min(1.4, zoom + 0.1))}
            className="p-1.5 rounded-lg text-[#D8C7F0] hover:text-white hover:bg-[#2C0854] transition-colors"
            title="Zoom In"
          >
            <ZoomIn className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={() => setZoom(1)}
            className="p-1.5 rounded-lg text-[#D8C7F0] hover:text-white hover:bg-[#2C0854] transition-colors ml-1"
            title="Reset"
          >
            <RotateCcw className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Bracket Tree Container */}
      <div className="w-full overflow-x-auto overflow-y-hidden pb-10 pt-6 rounded-3xl bg-[#17022E] border border-[#4A138C] p-6 sm:p-8 min-h-[500px] shadow-2xl">
        <div
          className="flex items-stretch gap-10 min-w-max transition-transform origin-top-left"
          style={{ transform: `scale(${zoom})` }}
        >
          {rounds.map((round, rIdx) => {
            const isFinal = rIdx === rounds.length - 1;
            return (
              <div key={round.roundNumber} className="flex flex-col w-72 shrink-0">
                {/* Round Header */}
                <div className="text-center pb-3 mb-5 border-b border-[#4A138C]">
                  <span className="text-[10px] font-mono text-[#FFBA00] uppercase tracking-widest font-black block">
                    Round {round.roundNumber}
                  </span>
                  <h4 className="text-base font-black font-display text-white">
                    {round.roundName}
                  </h4>
                  <span className="text-[11px] text-[#FDB095] font-mono">
                    {round.matches.length} {round.matches.length === 1 ? 'Championship Match' : 'Matches'}
                  </span>
                </div>

                {/* Match Cards Container */}
                <div className="flex flex-col justify-around flex-grow gap-6">
                  {round.matches.map((match) => (
                    <MatchNode
                      key={match._id}
                      match={match}
                      isFinal={isFinal}
                      isAdmin={isAdmin}
                    />
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

const MatchNode = ({ match, isFinal, isAdmin }) => {
  const isTeam1Winner = match.winnerTeam && match.team1 && (match.winnerTeam._id === match.team1._id || match.winnerTeam === match.team1._id);
  const isTeam2Winner = match.winnerTeam && match.team2 && (match.winnerTeam._id === match.team2._id || match.winnerTeam === match.team2._id);

  return (
    <div
      className={`rounded-2xl border p-4 transition-all ${
        match.status === 'live'
          ? 'bg-[#2C0854] border-emerald-500 shadow-lg shadow-emerald-500/10 ring-1 ring-emerald-400/50'
          : match.status === 'completed'
          ? 'bg-[#240547] border-[#FFBA00]/40 shadow-md'
          : match.status === 'bye'
          ? 'bg-[#20033E]/60 border-[#E5958E]/30'
          : 'bg-[#20033E] border-[#4A138C]'
      }`}
    >
      {/* Node Meta: Match # & Status */}
      <div className="flex items-center justify-between gap-2 pb-2.5 mb-2.5 border-b border-[#4A138C]/70 text-[10px]">
        <span className="font-mono font-bold text-[#FDB095]">M#{match.matchNumber}</span>
        <StatusBadge status={match.status} queuePosition={match.queuePosition} />
      </div>

      {/* Team 1 Slot */}
      <div
        className={`flex items-center justify-between p-2.5 rounded-xl mb-1.5 transition-all ${
          isTeam1Winner
            ? 'bg-[#FFBA00]/20 text-[#FFBA00] font-black border border-[#FFBA00]/50 shadow-sm'
            : match.team1
            ? 'bg-[#140129] text-white font-semibold'
            : 'bg-[#140129]/60 text-slate-500 italic'
        }`}
      >
        <span className="truncate text-xs pr-2">
          {match.team1 ? match.team1.name : 'Waiting for Round...'}
        </span>
        {isTeam1Winner && (
          <span className="text-[10px] font-mono font-black text-[#FFBA00] flex items-center gap-1 shrink-0">
            <Crown className="w-3 h-3" />
            <span>WINNER</span>
          </span>
        )}
      </div>

      {/* Team 2 Slot */}
      <div
        className={`flex items-center justify-between p-2.5 rounded-xl transition-all ${
          match.isBye
            ? 'bg-[#E5958E]/15 text-[#F5B7B1] italic border border-[#E5958E]/30'
            : isTeam2Winner
            ? 'bg-[#FFBA00]/20 text-[#FFBA00] font-black border border-[#FFBA00]/50 shadow-sm'
            : match.team2
            ? 'bg-[#140129] text-white font-semibold'
            : 'bg-[#140129]/60 text-slate-500 italic'
        }`}
      >
        <span className="truncate text-xs pr-2">
          {match.isBye ? 'BYE (Automatic Advance)' : match.team2 ? match.team2.name : 'Waiting for Round...'}
        </span>
        {isTeam2Winner && !match.isBye && (
          <span className="text-[10px] font-mono font-black text-[#FFBA00] flex items-center gap-1 shrink-0">
            <Crown className="w-3 h-3" />
            <span>WINNER</span>
          </span>
        )}
      </div>

      {/* Admin Quick Score Link */}
      {isAdmin && !match.isBye && match.team1 && match.team2 && (
        <div className="mt-2.5 pt-2.5 border-t border-[#4A138C]/70 flex justify-end">
          <Link
            href={`/admin/matches/${match._id}/score`}
            className="flex items-center gap-1 text-[11px] font-bold text-[#FFBA00] hover:text-[#FFC933] transition-colors"
          >
            <span>Referee Match</span>
            <ExternalLink className="w-3 h-3" />
          </Link>
        </div>
      )}
    </div>
  );
};
