'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useAuth } from '@/context/AuthContext';
import { Trophy, ExternalLink, ZoomIn, ZoomOut, RotateCcw, Crown, Shield, Play } from 'lucide-react';
import { StatusBadge, MainBoardBadge } from '@/components/ui/Badge';

export const BracketView = ({ rounds, category, isLocked, isPublished }) => {
  const { isAdmin } = useAuth();
  const [zoom, setZoom] = useState(1);

  if (!rounds || rounds.length === 0) {
    return (
      <div className="p-12 text-center arena-card rounded-3xl space-y-3">
        <Trophy className="w-12 h-12 text-[#F2C94C] mx-auto mb-2 opacity-80" />
        <h3 className="text-xl font-black text-white font-display uppercase tracking-wide">No Bracket Generated Yet</h3>
        <p className="text-xs text-[#F5F1E8]/70 max-w-sm mx-auto font-mono">
          The dynamic single-elimination knockout bracket for this category has not been generated by the tournament director yet.
        </p>
        {isAdmin && (
          <div className="mt-4">
            <Link
              href="/admin/draws"
              className="inline-flex items-center gap-2 px-6 py-3 rounded-2xl btn-gold text-xs font-black shadow-md"
            >
              Generate Draw in Admin →
            </Link>
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Top controls: Category status, Zoom */}
      <div className="flex flex-wrap items-center justify-between gap-3 p-4 rounded-2xl bg-[#14171A] border border-[#2A313C] shadow-lg">
        <div className="flex items-center gap-3">
          <span className="text-xs text-[#F5F1E8]/70 font-mono uppercase font-bold">Status:</span>
          {isLocked ? (
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-[11px] font-bold bg-[#F2C94C]/15 text-[#F2C94C] border border-[#F2C94C]/35 font-mono tracking-wider">
              <Shield className="w-3 h-3 text-[#F2C94C]" />
              <span>PUBLISHED & LOCKED</span>
            </span>
          ) : (
            <span className="inline-flex items-center px-3 py-1 rounded-full text-[11px] font-bold bg-[#D4A94C]/15 text-[#FFE2AA] border border-[#D4A94C]/35 font-mono tracking-wider">
              DRAFT / UNLOCKED
            </span>
          )}
          <span className="text-xs text-[#2A313C]">|</span>
          <span className="text-xs text-[#F5F1E8]/80 font-mono font-bold">{rounds.length} Knockout Rounds</span>
        </div>

        {/* Zoom controls */}
        <div className="flex items-center gap-1.5 bg-[#0B0D0E] p-1.5 rounded-xl border border-[#2A313C]">
          <button
            onClick={() => setZoom(Math.max(0.7, zoom - 0.1))}
            className="p-1.5 rounded-lg text-[#F5F1E8]/70 hover:text-white hover:bg-[#1A1E24] transition-colors cursor-pointer"
            title="Zoom Out"
          >
            <ZoomOut className="w-3.5 h-3.5" />
          </button>
          <span className="px-2 text-xs font-mono text-[#F2C94C] font-bold">{Math.round(zoom * 100)}%</span>
          <button
            onClick={() => setZoom(Math.min(1.4, zoom + 0.1))}
            className="p-1.5 rounded-lg text-[#F5F1E8]/70 hover:text-white hover:bg-[#1A1E24] transition-colors cursor-pointer"
            title="Zoom In"
          >
            <ZoomIn className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={() => setZoom(1)}
            className="p-1.5 rounded-lg text-[#F5F1E8]/70 hover:text-white hover:bg-[#1A1E24] transition-colors ml-1 cursor-pointer"
            title="Reset Zoom"
          >
            <RotateCcw className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Bracket Tree Container */}
      <div className="w-full overflow-x-auto overflow-y-hidden pb-12 pt-6 rounded-3xl bg-[#0E1013] border border-[#D4A94C]/25 p-6 sm:p-8 min-h-[550px] shadow-2xl relative">
        <div
          className="flex items-stretch gap-12 sm:gap-16 min-w-max transition-transform origin-top-left relative"
          style={{ transform: `scale(${zoom})` }}
        >
          {rounds.map((round, rIdx) => {
            const isFinal = rIdx === rounds.length - 1;
            return (
              <div key={round.roundNumber} className="flex flex-col w-72 shrink-0 relative">
                {/* Round Header */}
                <div className="text-center pb-3 mb-6 border-b border-[#2A313C]">
                  <span className="text-[10px] font-mono text-[#F2C94C] uppercase tracking-widest font-black block">
                    STAGE {round.roundNumber} OF {rounds.length}
                  </span>
                  <h4 className="text-lg font-black font-display text-white uppercase tracking-wide">
                    {round.roundName}
                  </h4>
                  <span className="text-[11px] text-[#F5F1E8]/60 font-mono">
                    {round.matches.length} {round.matches.length === 1 ? 'Championship Match' : 'Match Fixtures'}
                  </span>
                </div>

                {/* Match Cards Container */}
                <div className="flex flex-col justify-around flex-grow gap-8 relative">
                  {round.matches.map((match) => (
                    <MatchNode
                      key={match._id}
                      match={match}
                      isFinal={isFinal}
                      isAdmin={isAdmin}
                    />
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};

const MatchNode = ({ match, isFinal, isAdmin }) => {
  const isLive = match.status === 'live';
  const isCompleted = match.status === 'completed';
  const isScheduled = match.status === 'scheduled';
  const isBye = match.isBye || match.status === 'bye';

  const isTeam1Winner =
    match.winnerTeam && match.team1 && (match.winnerTeam._id === match.team1._id || match.winnerTeam === match.team1._id);
  const isTeam2Winner =
    match.winnerTeam && match.team2 && (match.winnerTeam._id === match.team2._id || match.winnerTeam === match.team2._id);

  return (
    <div
      className={`rounded-2xl border p-4 transition-all duration-200 ${
        isLive
          ? 'bg-[#1A1E24] border-rose-500 shadow-xl shadow-rose-950/40 ring-1 ring-rose-400/50'
          : isScheduled
          ? 'bg-[#14171A] border-[#F2C94C] shadow-lg shadow-[#F2C94C]/15'
          : isCompleted
          ? 'bg-[#111317]/90 border-[#2A313C] opacity-85'
          : isBye
          ? 'bg-[#14171A]/70 border-[#D4A94C]/30'
          : 'bg-[#14171A] border-[#2A313C]'
      }`}
    >
      {/* Node Meta: Match # & Status */}
      <div className="flex items-center justify-between gap-2 pb-2.5 mb-2.5 border-b border-[#2A313C] text-[10px]">
        <div className="flex items-center gap-1.5">
          <span className="font-mono font-black text-[#F2C94C] text-[11px]">M#{match.matchNumber}</span>
          {isFinal && (
            <span className="px-2 py-0.5 rounded-full bg-[#F2C94C]/20 text-[#F2C94C] font-bold uppercase font-mono text-[9px]">
              FINAL
            </span>
          )}
        </div>
        <StatusBadge status={match.status} queuePosition={match.queuePosition} />
      </div>

      {/* Team 1 Slot */}
      <div
        className={`flex items-center justify-between p-2.5 rounded-xl mb-1.5 transition-all ${
          isTeam1Winner
            ? 'bg-[#F2C94C]/20 text-[#F2C94C] font-black border border-[#F2C94C]/60 shadow-sm'
            : match.team1
            ? 'bg-[#1A1E24] text-white font-bold'
            : 'bg-[#14171A]/60 text-[#F5F1E8]/40 italic'
        }`}
      >
        <span className="truncate text-xs pr-2">
          {match.team1 ? match.team1.name : 'Waiting for Round Winner...'}
        </span>
        {isTeam1Winner && (
          <span className="text-[10px] font-mono font-black text-[#F2C94C] flex items-center gap-1 shrink-0">
            <Crown className="w-3 h-3" />
            <span>WINNER</span>
          </span>
        )}
      </div>

      {/* Team 2 Slot */}
      <div
        className={`flex items-center justify-between p-2.5 rounded-xl transition-all ${
          isBye
            ? 'bg-[#D4A94C]/15 text-[#FFECC7] italic border border-[#D4A94C]/30'
            : isTeam2Winner
            ? 'bg-[#F2C94C]/20 text-[#F2C94C] font-black border border-[#F2C94C]/60 shadow-sm'
            : match.team2
            ? 'bg-[#1A1E24] text-white font-bold'
            : 'bg-[#14171A]/60 text-[#F5F1E8]/40 italic'
        }`}
      >
        <span className="truncate text-xs pr-2">
          {isBye ? 'BYE (Automatic Advance)' : match.team2 ? match.team2.name : 'Waiting for Round Winner...'}
        </span>
        {isTeam2Winner && !isBye && (
          <span className="text-[10px] font-mono font-black text-[#F2C94C] flex items-center gap-1 shrink-0">
            <Crown className="w-3 h-3" />
            <span>WINNER</span>
          </span>
        )}
      </div>

      {/* Admin Referee Action */}
      {isAdmin && !isBye && match.team1 && match.team2 && (
        <div className="mt-2.5 pt-2.5 border-t border-[#2A313C] flex justify-end">
          <Link
            href={`/admin/matches/${match._id}/score`}
            className="flex items-center gap-1 text-[11px] font-mono font-bold text-[#F2C94C] hover:underline transition-colors uppercase tracking-wider"
          >
            <span>Score Desk</span>
            <ExternalLink className="w-3 h-3" />
          </Link>
        </div>
      )}
    </div>
  );
};
