'use client';

import React from 'react';
import Link from 'next/link';

export function RecentMatchesTable({ matches = [], loading = false }) {
  return (
    <div className="bg-white dark:bg-[#121215] border border-[#E5E5E5] dark:border-[#27272A] rounded-2xl p-5 shadow-xs space-y-4 transition-colors">
      
      {/* Title */}
      <div className="flex items-center justify-between">
        <h3 className="text-xs font-bold font-display text-[#111111] dark:text-[#F4F4F5] tracking-wider uppercase">
          RECENT MATCHES
        </h3>
        <Link href="/chess/matches" className="text-xs font-mono font-bold text-[#C9A227] hover:underline">
          View All ({matches.length})
        </Link>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse text-xs">
          <thead>
            <tr className="border-b border-[#E5E5E5] dark:border-[#27272A] text-[#666666] dark:text-[#A1A1AA] font-mono uppercase text-[10px]">
              <th className="py-2.5 px-3">Match ID</th>
              <th className="py-2.5 px-3 text-center">Round</th>
              <th className="py-2.5 px-3">Player 1</th>
              <th className="py-2.5 px-3">Player 2</th>
              <th className="py-2.5 px-3 text-center">Status</th>
              <th className="py-2.5 px-3 text-center">Result</th>
              <th className="py-2.5 px-3 text-right">Score</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#E5E5E5] dark:divide-[#27272A]">
            {loading ? (
              <tr>
                <td colSpan={7} className="py-10 text-center text-[#666666] dark:text-[#A1A1AA]">
                  Loading live match records...
                </td>
              </tr>
            ) : matches.length === 0 ? (
              <tr>
                <td colSpan={7} className="py-10 text-center text-[#666666] dark:text-[#A1A1AA]">
                  No match records available yet. Pairings will appear once generated by admin.
                </td>
              </tr>
            ) : (
              matches.map((m) => {
                const p1 = m.player1?.fullName || (m.isBye ? (m.byePlayer?.fullName || 'Player') : 'TBD');
                const p2 = m.player2?.fullName || (m.isBye ? 'BYE' : 'TBD');
                const isCompleted = m.status === 'completed';
                const isLive = m.status === 'live';

                let winnerText = '-';
                if (isCompleted) {
                  if (m.isBye) winnerText = 'BYE (+3)';
                  else if (m.winner === 'player1') winnerText = `${p1.split(' ')[0]} Won`;
                  else if (m.winner === 'player2') winnerText = `${p2.split(' ')[0]} Won`;
                  else if (m.winner === 'draw') winnerText = 'Draw';
                  else winnerText = 'Completed';
                }

                const scoreStr = `${m.player1MaterialScore || 0} - ${m.player2MaterialScore || 0}`;

                return (
                  <tr key={m._id || m.matchId} className="hover:bg-gray-50 dark:hover:bg-[#18181C] transition-colors">
                    <td className="py-3 px-3 font-mono font-bold text-[#111111] dark:text-[#F4F4F5]">
                      <Link href={`/chess/matches/${m._id || m.matchId}`} className="hover:text-[#C9A227]">
                        {m.matchId}
                      </Link>
                    </td>
                    <td className="py-3 px-3 text-center font-mono text-[#666666] dark:text-[#A1A1AA]">
                      {m.round}
                    </td>
                    <td className="py-3 px-3 font-semibold text-[#111111] dark:text-[#F4F4F5]">
                      {p1}
                    </td>
                    <td className="py-3 px-3 font-semibold text-[#111111] dark:text-[#F4F4F5]">
                      {p2}
                    </td>
                    <td className="py-3 px-3 text-center">
                      {isCompleted ? (
                        <span className="badge-completed px-2 py-0.5 rounded-full text-[10px] font-mono font-bold">
                          Completed
                        </span>
                      ) : isLive ? (
                        <span className="badge-live px-2 py-0.5 rounded-full text-[10px] font-mono font-bold">
                          Live
                        </span>
                      ) : (
                        <span className="bg-gray-100 dark:bg-[#18181C] text-gray-700 dark:text-gray-300 px-2 py-0.5 rounded-full text-[10px] font-mono border border-[#E5E5E5] dark:border-[#27272A]">
                          Scheduled
                        </span>
                      )}
                    </td>
                    <td className="py-3 px-3 text-center font-bold text-[#C9A227]">
                      {winnerText}
                    </td>
                    <td className="py-3 px-3 text-right font-mono font-bold text-[#111111] dark:text-[#F4F4F5]">
                      {scoreStr}
                    </td>
                  </tr>
                );
              })
            )}
          </tbody>
        </table>
      </div>

    </div>
  );
}
